/* eslint-disable import/no-anonymous-default-export */
const API_BASE_URL = 'http://localhost:5000'

const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST'
const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL'
const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL'
const AUTH_LOGOUT = 'AUTH_LOGOUT'
const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'
const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST'
const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'
const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL'
const GET_CURRENT_PROFILE_REQUEST = 'GET_CURRENT_PROFILE_REQUEST'
const GET_CURRENT_PROFILE_SUCCESS = 'GET_CURRENT_PROFILE_SUCCESS'
const GET_CURRENT_PROFILE_FAIL = 'GET_CURRENT_PROFILE_FAIL'
const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST'
const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL'
const GET_TASK_REQUEST = 'GET_TASK_REQUEST'
const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'
const GET_TASK_FAIL = 'GET_TASK_FAIL'
const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL'
const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL'
const SET_ACTIVE_TASK_TAB = 'SET_ACTIVE_TASK_TAB'
const GET_ALL_TASK_BY_USER_REQUEST = 'GET_ALL_TASK_BY_USER_REQUEST'
const GET_ALL_TASK_BY_USER_SUCCESS = 'GET_ALL_TASK_BY_USER_SUCCESS'
const GET_ALL_TASK_BY_USER_FAIL = 'GET_ALL_TASK_BY_USER_FAIL'
const GET_ALL_TASK_REQUEST = 'GET_ALL_TASK_REQUEST'
const GET_ALL_TASK_SUCCESS = 'GET_ALL_TASK_SUCCESS'
const GET_ALL_TASK_FAIL = 'GET_ALL_TASK_FAIL'
const RESET_GET_TASKS = 'RESET_GET_TASKS'
const SET_DATES_LEAVE = 'SET_DATES_LEAVE'
const CREATE_LEAVE_REQUEST = 'CREATE_LEAVE_REQUEST'
const CREATE_LEAVE_SUCCESS = 'CREATE_LEAVE_SUCCESS'
const CREATE_LEAVE_FAIL = 'CREATE_LEAVE_FAIL'
const GET_CURRENT_LEAVE_REQUEST = 'GET_CURRENT_LEAVE_REQUEST'
const GET_CURRENT_LEAVE_SUCCESS = 'GET_CURRENT_LEAVE_SUCCESS'
const GET_CURRENT_LEAVE_FAIL = 'GET_CURRENT_LEAVE_FAIL'
const GET_ALL_LEAVE_REQUEST = 'GET_ALL_LEAVE_REQUEST'
const GET_ALL_LEAVE_SUCCESS = 'GET_ALL_LEAVE_SUCCESS'
const GET_ALL_LEAVE_FAIL = 'GET_ALL_LEAVE_FAIL'
const DELETE_LEAVE_REQUEST = 'DELETE_LEAVE_REQUEST'
const DELETE_LEAVE_SUCCESS = 'DELETE_LEAVE_SUCCESS'
const DELETE_LEAVE_FAIL = 'DELETE_LEAVE_FAIL'
const APPROVE_LEAVE_REQUEST = 'APPROVE_LEAVE_REQUEST'
const APPROVE_LEAVE_SUCCESS = 'APPROVE_LEAVE_SUCCESS'
const APPROVE_LEAVE_FAIL = 'APPROVE_LEAVE_FAIL'
const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'
const DELETE_PROFILE_REQUEST = 'DELETE_PROFILE_REQUEST'
const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS'
const DELETE_PROFILE_FAIL = 'DELETE_PROFILE_FAIL'

const ERROR_MESSAGE = 'Opps...Something went wrong, Please try again later'

export {
  API_BASE_URL,
  AUTH_LOGIN_REQUEST,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAIL,
  AUTH_LOGOUT,
  AUTH_REGISTER_REQUEST,
  AUTH_REGISTER_SUCCESS,
  AUTH_REGISTER_FAIL,
  GET_PROFILE_REQUEST,
  GET_PROFILE_SUCCESS,
  GET_PROFILE_FAIL,
  CREATE_PROFILE_REQUEST,
  CREATE_PROFILE_SUCCESS,
  CREATE_PROFILE_FAIL,
  GET_CURRENT_PROFILE_REQUEST,
  GET_CURRENT_PROFILE_SUCCESS,
  GET_CURRENT_PROFILE_FAIL,
  CREATE_TASK_REQUEST,
  CREATE_TASK_SUCCESS,
  CREATE_TASK_FAIL,
  GET_TASK_REQUEST,
  GET_TASK_SUCCESS,
  GET_TASK_FAIL,
  SET_ACTIVE_TASK_TAB,
  UPDATE_TASK_REQUEST,
  UPDATE_TASK_SUCCESS,
  UPDATE_TASK_FAIL,
  DELETE_TASK_REQUEST,
  DELETE_TASK_SUCCESS,
  DELETE_TASK_FAIL,
  GET_ALL_TASK_BY_USER_REQUEST,
  GET_ALL_TASK_BY_USER_SUCCESS,
  GET_ALL_TASK_BY_USER_FAIL,
  GET_ALL_TASK_REQUEST,
  GET_ALL_TASK_SUCCESS,
  GET_ALL_TASK_FAIL,
  RESET_GET_TASKS,
  SET_DATES_LEAVE,
  CREATE_LEAVE_REQUEST,
  CREATE_LEAVE_SUCCESS,
  CREATE_LEAVE_FAIL,
  GET_CURRENT_LEAVE_REQUEST,
  GET_CURRENT_LEAVE_SUCCESS,
  GET_CURRENT_LEAVE_FAIL,
  GET_ALL_LEAVE_REQUEST,
  GET_ALL_LEAVE_SUCCESS,
  GET_ALL_LEAVE_FAIL,
  DELETE_LEAVE_REQUEST,
  DELETE_LEAVE_SUCCESS,
  DELETE_LEAVE_FAIL,
  APPROVE_LEAVE_REQUEST,
  APPROVE_LEAVE_SUCCESS,
  APPROVE_LEAVE_FAIL,
  UPDATE_PROFILE_REQUEST,
  UPDATE_PROFILE_SUCCESS,
  UPDATE_PROFILE_FAIL,
  DELETE_PROFILE_REQUEST,
  DELETE_PROFILE_SUCCESS,
  DELETE_PROFILE_FAIL,
  ERROR_MESSAGE,
}
